# Generated by Django 2.2.4 on 2022-07-16 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data4u', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_4',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question_4',
            name='user_point',
            field=models.IntegerField(default=0),
        ),
    ]
