# Generated by Django 2.2.4 on 2022-07-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data4u', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_4',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
