# Generated by Django 2.2.4 on 2022-07-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data4u', '0005_auto_20220718_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.IntegerField(),
        ),
    ]
